name: Deploy to OpenShift

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install oc CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xvf oc.tar.gz
        sudo mv oc /usr/local/bin

    - name: Login to OpenShift
      run: |
        oc login ${{ secrets.OPENSHIFT_SERVER }} \
          --token=${{ secrets.OPENSHIFT_TOKEN }} \
          --insecure-skip-tls-verify=true

    - name: Set project
      run: oc project ${{ secrets.OPENSHIFT_NAMESPACE }}

    - name: Apply OpenShift YAML
      run: |
        oc apply -f k8s/app.yaml

    - name: Restart deployment
      run: oc rollout restart deployment photoalbum-git